### ISSUE TITLE
Allows not capturing

### ISSUE THREAD

**Issue by Gaming32** [jmsheff/discord-checkers#1]
The checkers bot allows you to not capture a piece when you are able to. However, the checkers rules require that, if you can capture a piece, you *must* capture it.

**Comment by jmsheff** [comment]
Yes, this was something I did not account for originally by design, as it is how I always personally played. Stay tuned for an update however where this can be configured.

**Comment by Gaming32** [comment]
The configuration should default to on for forcing captures, otherwise that could annoy players (e.g. me).
